/**
 * Deliberately small same-origin task console.  It contains no framework state
 * and keeps an API key only in sessionStorage, so it is a usable demo surface
 * rather than a second product runtime.
 */
export function dashboardResponse(): Response {
    return new Response(DASHBOARD_HTML, {
        headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" },
    });
}

// Do not use String.raw here: Bun may emit non-ASCII source literals as
// \uXXXX escapes, and a raw template would send those escape sequences to the
// browser as visible text instead of decoding them into Chinese characters.
const DASHBOARD_HTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VRAM-Aware Harness · Task Console</title><style>
:root{--ink:#17231f;--muted:#65716b;--line:#d5ddd6;--paper:#f2f4ef;--green:#173f35;--accent:#d8f27a;--danger:#b6432e}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px Arial,"PingFang SC",sans-serif}.shell{width:min(1060px,calc(100% - 32px));margin:auto}.top{background:var(--green);color:#fff;padding:20px 0}.top div{display:flex;justify-content:space-between;gap:18px;align-items:center}.top b{letter-spacing:.07em}.top span{color:#bfcdc5;font-size:12px}main{padding:34px 0 64px}.intro{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:25px}.intro h1{font:500 38px Georgia,"Songti SC",serif;margin:0}.intro p{max-width:520px;color:var(--muted);line-height:1.6}.grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:18px}.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:20px;box-shadow:0 12px 32px #17231f0d}.card h2{font-size:12px;letter-spacing:.09em;margin:0 0 16px;color:var(--green)}label{display:grid;gap:7px;color:var(--muted);font-size:12px;margin:12px 0}input,textarea,select{font:inherit;border:1px solid #b9c5bd;border-radius:7px;padding:10px;width:100%;background:#fff;color:var(--ink)}textarea{min-height:122px;resize:vertical}button{border:0;border-radius:7px;padding:10px 13px;background:var(--green);color:#fff;font-weight:700;cursor:pointer}button:hover{filter:brightness(1.13)}button.secondary{background:#e6ebe6;color:var(--green)}button.danger{background:var(--danger)}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.status{font-size:12px;color:var(--muted);min-height:20px}.status.error{color:var(--danger)}.workspaceList{padding:0;margin:14px 0 0;list-style:none;display:grid;gap:7px}.workspaceList button{width:100%;text-align:left;background:#eef3ed;color:var(--green);font-weight:600}.runHeader{display:flex;gap:10px;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:12px}.badge{padding:5px 8px;border-radius:99px;background:#e8eee7;color:var(--green);font-size:11px;font-weight:800}.panel{margin-top:16px}.panel h3{font-size:12px;margin:0 0 8px;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;min-height:76px;margin:0;background:#12221d;color:#d8eee1;padding:12px;border-radius:8px;font:12px ui-monospace,SFMono-Regular,monospace}.diff{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.diff div{border:1px solid var(--line);padding:10px;border-radius:7px}.diff b{display:block;font-size:20px;color:var(--green)}.hidden{display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.intro{display:block}.intro h1{font-size:32px}.top div{align-items:start;flex-direction:column}}
</style></head><body><header class="top"><div class="shell"><b>VH · TASK CONSOLE</b><span>同源最小界面 · API Key 仅保存至本次浏览器会话</span></div></header><main class="shell"><section class="intro"><div><h1>提交任务，看到它如何结束。</h1><p>为受管 Workspace 创建任务，查看排队/运行状态、文本输出与文件 Diff。所有请求仍由 API Key 派生 Tenant，页面不接受 tenantId。</p></div><a href="/health">服务健康状态</a></section><div class="grid"><aside class="card"><h2>01 · 连接与 Workspace</h2><label>API Key<input id="key" type="password" autocomplete="off" placeholder="仅保存在本次会话"></label><div class="row"><button id="connect">读取 Workspace 与任务</button><span id="connection" class="status"></span></div><label>新 Workspace 名称<input id="workspaceName" placeholder="例如 demo-project"></label><button id="createWorkspace">创建 Workspace</button><ul id="workspaces" class="workspaceList"></ul></aside><section class="card"><h2>02 · 创建 Agent Task</h2><label>当前 Workspace<select id="workspaceSelect"><option value="">先读取或创建 Workspace</option></select></label><label>任务描述<textarea id="task" placeholder="例如：检查项目中的测试失败原因，修复后运行测试，并总结变更。"></textarea></label><div class="row"><button id="submit">提交任务</button><span id="submitStatus" class="status"></span></div><section id="runCard" class="hidden"><div class="runHeader"><div><strong id="runId"></strong><span id="runStatus" class="badge"></span></div><button id="interrupt" class="danger">中断</button></div><div class="panel"><h3>模型输出（轮询读取持久化 chunks）</h3><pre id="output">等待任务输出…</pre></div><div class="panel"><h3>Workspace Diff（仅文件路径、哈希和大小，不暴露正文）</h3><div class="diff"><div><b id="added">0</b>新增</div><div><b id="modified">0</b>修改</div><div><b id="deleted">0</b>删除</div></div></div></section></section></div><section class="card panel"><h2>03 · 我的任务历史</h2><ul id="runs" class="workspaceList"></ul></section></main><script>
const $=id=>document.getElementById(id);let currentRun=null, timer=null;
$('key').value=sessionStorage.getItem('vh-api-key')||'';
function headers(){const key=$('key').value.trim();if(!key)throw new Error('请先输入 API Key');sessionStorage.setItem('vh-api-key',key);return {'authorization':'Bearer '+key,'content-type':'application/json'}}
async function api(path,options={}){const res=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});const body=await res.json().catch(()=>({error:'服务返回非 JSON'}));if(!res.ok)throw new Error(body.error||('HTTP '+res.status));return body}
function setStatus(id,text,error=false){const el=$(id);el.textContent=text;el.className='status'+(error?' error':'')}
async function loadWorkspaces(){try{const {workspaces}=await api('/workspaces');const select=$('workspaceSelect'),list=$('workspaces');select.innerHTML='<option value="">选择 Workspace</option>';list.innerHTML='';workspaces.forEach(w=>{const o=document.createElement('option');o.value=w.id;o.textContent=w.name;select.append(o);const b=document.createElement('button');b.textContent=w.name;b.onclick=()=>select.value=w.id;const li=document.createElement('li');li.append(b);list.append(li)});setStatus('connection','已连接：'+workspaces.length+' 个 Workspace')}catch(e){setStatus('connection',e.message,true)}}
async function loadRuns(){try{const {runs}=await api('/runs');const list=$('runs');list.innerHTML='';runs.forEach(run=>{const b=document.createElement('button');b.textContent=run.status+' · '+run.userInput.slice(0,72);b.onclick=async()=>{currentRun=run.id;$('runCard').classList.remove('hidden');$('runId').textContent='Run '+run.id;await refresh()};const li=document.createElement('li');li.append(b);list.append(li)})}catch(e){setStatus('connection',e.message,true)}}
$('connect').onclick=async()=>{await loadWorkspaces();await loadRuns()};$('createWorkspace').onclick=async()=>{try{const name=$('workspaceName').value.trim();if(!name)throw new Error('请输入 Workspace 名称');const {workspace}=await api('/workspaces',{method:'POST',body:JSON.stringify({name})});$('workspaceName').value='';await loadWorkspaces();$('workspaceSelect').value=workspace.id;setStatus('connection','已创建 '+workspace.name)}catch(e){setStatus('connection',e.message,true)}};
async function refresh(){if(!currentRun)return;try{const [{run},{finalText},{diff}]=await Promise.all([api('/runs/'+currentRun),api('/runs/'+currentRun+'/output'),api('/runs/'+currentRun+'/workspace-diff')]);$('runStatus').textContent=run.status;$('output').textContent=finalText||'等待模型输出…';$('added').textContent=diff?.added?.length||0;$('modified').textContent=diff?.modified?.length||0;$('deleted').textContent=diff?.deleted?.length||0;if(['COMPLETED','FAILED','INTERRUPTED'].includes(run.status)){clearInterval(timer);timer=null}}catch(e){setStatus('submitStatus',e.message,true)}}
$('submit').onclick=async()=>{try{const workspaceId=$('workspaceSelect').value,userInput=$('task').value.trim();if(!workspaceId||!userInput)throw new Error('请选择 Workspace 并输入任务');const {run}=await api('/runs',{method:'POST',body:JSON.stringify({workspaceId,userInput})});currentRun=run.id;$('runCard').classList.remove('hidden');$('runId').textContent='Run '+run.id;$('runStatus').textContent=run.status;setStatus('submitStatus','任务已进入调度队列');if(timer)clearInterval(timer);await refresh();await loadRuns();timer=setInterval(refresh,1200)}catch(e){setStatus('submitStatus',e.message,true)}};
$('interrupt').onclick=async()=>{if(!currentRun)return;try{await api('/runs/'+currentRun+'/interrupt',{method:'POST'});await refresh()}catch(e){setStatus('submitStatus',e.message,true)}};
</script></body></html>`;
